"""
Weather CLI - CLI Interface
Generated by OCEAN using Codex MCP
"""

class CLIInterface:
    def __init__(self):
        self.commands = {}
        
    def add_command(self, name, handler):
        """Add a CLI command"""
        self.commands[name] = handler
        
    def run(self):
        """Run the CLI interface"""
        print("CLI interface implementation goes here...")
        print("Generated by OCEAN using Codex MCP")
