#!/usr/bin/env python3
"""
Weather CLI - CLI Application
Generated by OCEAN using Codex MCP
"""

import click
from game import Game

@click.command()
@click.option("--difficulty", default="normal", help="Game difficulty")
@click.option("--config", default="config.json", help="Config file path")
def main(difficulty, config):
    """A command-line weather application that fetches and displays weather data"""
    game = Game(difficulty=difficulty, config_file=config)
    game.run()

if __name__ == "__main__":
    main()
