from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="dyno game", version="0.1.0")

# Enable CORS for development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get('/')
def root():
    return {"message": "Welcome to dyno game", "type": "web"}

@app.get('/healthz')
def healthz():
    return {'ok': True, 'status': 'healthy'}

# TODO: Add more endpoints based on project requirements
# Generated by OCEAN using Codex MCP
