version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:ro
    env_file:
      - .env
    environment:
      - ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 5s
      timeout: 2s
      retries: 10
  ui:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - backend
