#!/usr/bin/env python3
"""Write ``ocean/_release_embedded.py`` from ``OCEAN_RELEASE_GEMINI_KEY``.

Run **only** in private release CI before ``pip wheel`` / packaging so the wheel
contains a non-empty embedded setup key. Public ``main`` must keep the stub
empty — never commit a live key to git.

Usage::

    export OCEAN_RELEASE_GEMINI_KEY='...'
    python scripts/embed_release_gemini_key.py
"""

from __future__ import annotations

import os
from pathlib import Path


def main() -> None:
    key = os.environ.get("OCEAN_RELEASE_GEMINI_KEY", "").strip()
    if not key:
        raise SystemExit("OCEAN_RELEASE_GEMINI_KEY must be set to a non-empty value")
    root = Path(__file__).resolve().parents[1]
    out = root / "ocean" / "_release_embedded.py"
    body = (
        '"""Auto-generated by scripts/embed_release_gemini_key.py — '
        'do not commit a real key to public git."""\n\n'
        "EMBEDDED_GEMINI_SETUP_KEY: str = "
        + repr(key)
        + "\n"
    )
    out.write_text(body, encoding="utf-8")
    print(f"Wrote {out} (key length {len(key)})")


if __name__ == "__main__":
    main()
